In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [7]:
data = pd.read_csv("1.02.+Multiple+linear+regression.csv")

In [8]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [9]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [10]:
x = data[['SAT', 'Rand 1,2,3']]
y = data['GPA']


In [11]:
reg = LinearRegression()

In [12]:
reg.fit(x, y)

LinearRegression()

In [13]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [14]:
reg.intercept_


0.29603261264909353

In [15]:
reg.score(x, y) #R-Squared

0.4066811952814282

## Formula for Adjusted R-Squared

$R^2_{adj.} = 1 - (1 - R ^ 2)*\frac{n-1}{n-p-1}$

In [16]:
x.shape # n = number of observations // p = number of predictors

(84, 2)

In [17]:
def adjscore(rsquared):
    rsq = rsquared
    n = x.shape[0]
    p = x.shape[1]
    adjscore = 1 - (1 - rsq) * (n - 1) / (n - p - 1)
    return adjscore

In [18]:
adjscore(reg.score(x, y))

0.39203134825134

## F-Regression

In [19]:
from sklearn.feature_selection import f_regression

In [20]:
f_regression(x, y) # Array 1 -> F-Statistics | Array 2 -> P-Values -- Respectively

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [22]:
p_values = f_regression(x, y)[1]

In [23]:
p_values

array([7.19951844e-11, 6.76291372e-01])

#### First P-Value (SAT) is < 0.05 (use
#### Second P-Value (RAND) is > 0.05 which insignificant

In [25]:
p_values.round(3)

array([0.   , 0.676])

In [26]:
p_SAT = p_values.round(3)[0]

In [27]:
p_RAND = p_values.round(3)[1]

In [28]:
p_SAT

0.0

In [30]:
p_RAND

0.676